### ISSUE TITLE
trouble while compiling

### ISSUE THREAD

**Issue by ragnar76** [th-otto/gemfedit#1]
After installing Vincents m68k-atari-mint cross-tools (http://vincent.riviere.free.fr/soft/m68k-atari-mint/debian.php), i had to install some deps and symlinks (libc.so.6 and libdl.so.2 is not in /lib64 anymore) i stumbled across this error which i'm not able to solve myself:

`ragnar@z13:~/src/gemfedit$ make
for i in fonts include zlib libpng freetype tools tos unix win32 speedo spdview; do make -C $i all || exit 1; done
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/fonts“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/fonts“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/include“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/include“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/zlib“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/zlib“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/libpng“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/libpng“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/freetype“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/freetype“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/tools“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/tools“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/tos“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/tos“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/unix“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/unix“ wird verlassen
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/win32“ wird betreten
i686-pc-mingw32-gcc -mwin32 -O2 -Wall -I../libpng -I../zlib -I../include -DHAVE_PNG_H -DZLIB_STATIC fontdisp.c -c -o fontdisp.o
make[1]: i686-pc-mingw32-gcc: Datei oder Verzeichnis nicht gefunden
make[1]: *** [Makefile:16: fontdisp.o] Fehler 127
make[1]: Verzeichnis „/home/ragnar/src/gemfedit/win32“ wird verlassen
make: *** [Makefile:8: all] Fehler 1
`

I'd like to build linux only, so do i miss some options like "make unix"?

**Comment by th-otto** [comment]
You could just remove "win32" (and also "tos" if you dont need it) from the list of sub-directories to build in the toplevel Makefile. But should be fixed now.

**Comment by ragnar76** [comment]
Works now. Thank you :+1:
